### ISSUE TITLE
hi,你好小工具很不错

### ISSUE THREAD

**Issue by cqworker** [nocpp/birthbook#1]
我更关心的是如何从vue打包为apk，方便给我一点建议吗

**Comment by nocpp** [comment]
你好，谢谢支持。H5项目打包成app有很多办法。
1. 通过原生开发工具打包，比如Android Studio和Xcode, 这个需要懂一点原生
2. 通过第三方混合开发平台打包，我现在是这么做的
我用的是Dcloud平台的HbuilderX进行打包的
Dcloud:   https://www.dcloud.io/
下载他们的HbuilderX工具，然后新建H5+项目，
把Vue项目编译的源码复制到刚刚建的项目目录下，
然后点发现，云打包就可了

**Comment by cqworker** [comment]
好的 谢谢你的回答
